import com.car.Car;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    
    public static void main(String[] args) {
    	Car car = new Car("v12","miqilin"); 
    	System.out.println(car.start());
    }
}
