import com.car.Car;
import com.car.SportCar;
import com.car.Truck;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    
    public static void main(String[] args) {
    	Car car = new Car("v12","miqilin"); 
    	System.out.println(car.start());
    	SportCar sportcar = new SportCar("v20","niubi","ö¦ö¦ö¦");
    	System.out.println(sportcar.start());
    	System.out.println(sportcar.speedOn());
    	Truck truck = new Truck("v6","´óÂÖ×Ó","»õÏä");
    	System.out.println(truck.start());
    	System.out.println(truck.load());
    }
}
